### ISSUE TITLE
Access to Pretrained BERT Models

### ISSUE THREAD

**Issue by rama-challa** [kuppulur/Telugu_Experiments#1]
Hi,

A very useful work for anyone who wants to work on data in Telugu.

Could you share the location access the pretrained BERT models (ex. telugu_bertu_pos, telugu_bertu_ner, telugu_bertu)?

TIA!

**Comment by kuppulur** [comment]
Hi Rama-Challa,

Thank you! All the models are available via huggingface model repository https://huggingface.co/kuppuluri. The code should auto-download all the models.
